name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "test"
      suite:
        description: "Suite"
        required: true
        default: "smoke"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.suite }}" = "smoke" ]; then
            ENVIRONMENT=${{ github.event.inputs.environment }} npx playwright test tests/smoke
          else
            ENVIRONMENT=${{ github.event.inputs.environment }} npx playwright test
          fi